-- Communications layer and sign-in by one-time code (deliverable 16, docs/16-communications.md).
-- Folded into db/schema.sql as well; this file brings existing databases up to date.
-- The seeded template library is appended at the end (generated by packages/comms, same as db/seed.sql).

-- core: lookups by topic and aggregate (reminders, overdue alerts, ending-soon alerts) -------------
CREATE INDEX outbox_topic_aggregate_idx ON core.outbox (topic, aggregate_id);

-- identity: one-time code challenges ---------------------------------------------------------------
-- The code is never stored. code_hmac verifies a typed code; code_salt lets the sender derive the
-- same code again with the server secret (docs/16 §9). Both are useless without that secret.
CREATE TABLE identity.otp_challenge (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purpose          text NOT NULL CHECK (purpose IN ('sign_in', 'add_contact')),
  destination_type text NOT NULL CHECK (destination_type IN ('phone', 'email')),
  destination      text NOT NULL,                -- E.164 phone or lower-case email
  account_id       uuid REFERENCES identity.account (id),
  code_salt        bytea NOT NULL CHECK (octet_length(code_salt) >= 16),
  code_hmac        bytea NOT NULL CHECK (octet_length(code_hmac) = 32),
  code_length      integer NOT NULL CHECK (code_length BETWEEN 4 AND 10),
  ip_hmac          bytea,
  status           text NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending', 'verified', 'expired', 'locked', 'superseded')),
  attempts         integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  max_attempts     integer NOT NULL CHECK (max_attempts > 0),
  send_count       integer NOT NULL DEFAULT 1 CHECK (send_count >= 1),
  max_sends        integer NOT NULL CHECK (max_sends > 0),
  last_sent_at     timestamptz NOT NULL,
  created_at       timestamptz NOT NULL,
  expires_at       timestamptz NOT NULL,
  verified_at      timestamptz,
  CHECK (expires_at > created_at),
  CHECK (attempts <= max_attempts),
  CHECK (send_count <= max_sends),
  CHECK ((status = 'verified') = (verified_at IS NOT NULL)),
  CHECK (verified_at IS NULL OR verified_at <= expires_at),
  CHECK (status <> 'locked' OR attempts = max_attempts),
  CHECK (destination_type <> 'phone' OR destination ~ '^\+[1-9][0-9]{6,14}$'),
  CHECK (destination_type <> 'email' OR (destination = lower(destination) AND destination ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')),
  CHECK (purpose <> 'add_contact' OR account_id IS NOT NULL)
);
-- At most one live challenge per phone number or email address.
CREATE UNIQUE INDEX otp_challenge_pending_uniq ON identity.otp_challenge (destination) WHERE status = 'pending';
CREATE INDEX otp_challenge_destination_idx ON identity.otp_challenge (destination, created_at);
CREATE INDEX otp_challenge_ip_idx ON identity.otp_challenge (ip_hmac, created_at) WHERE ip_hmac IS NOT NULL;

-- A challenge's terms never change; attempts and sends only go up; a finished challenge is final.
CREATE FUNCTION identity.guard_otp_challenge() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.status <> 'pending' THEN
    RAISE EXCEPTION 'one-time code challenge is %; it cannot change', OLD.status USING ERRCODE = 'restrict_violation';
  END IF;
  IF (NEW.purpose, NEW.destination_type, NEW.destination, NEW.code_salt, NEW.code_hmac, NEW.code_length,
      NEW.max_attempts, NEW.max_sends, NEW.created_at, NEW.expires_at, NEW.ip_hmac)
     IS DISTINCT FROM
     (OLD.purpose, OLD.destination_type, OLD.destination, OLD.code_salt, OLD.code_hmac, OLD.code_length,
      OLD.max_attempts, OLD.max_sends, OLD.created_at, OLD.expires_at, OLD.ip_hmac) THEN
    RAISE EXCEPTION 'one-time code challenge terms are immutable' USING ERRCODE = 'restrict_violation';
  END IF;
  IF OLD.account_id IS NOT NULL AND NEW.account_id IS DISTINCT FROM OLD.account_id THEN
    RAISE EXCEPTION 'one-time code challenge account cannot change' USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW.attempts < OLD.attempts OR NEW.send_count < OLD.send_count OR NEW.last_sent_at < OLD.last_sent_at THEN
    RAISE EXCEPTION 'one-time code attempts and sends never go down' USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER otp_challenge_guard BEFORE UPDATE ON identity.otp_challenge
  FOR EACH ROW EXECUTE FUNCTION identity.guard_otp_challenge();
CREATE TRIGGER otp_challenge_audit AFTER INSERT OR UPDATE ON identity.otp_challenge
  FOR EACH ROW EXECUTE FUNCTION audit.log_state_change('status');

-- comms: templates -----------------------------------------------------------------------------------

-- GSM 03.38 basic character set plus its extension table: an SMS in these characters fits
-- 160 per segment. Anything else forces UCS-2 (70 per segment) or is mangled by some networks.
CREATE FUNCTION comms.is_gsm7(p text) RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
  SELECT translate(p, '@£$¥èéùìòÇØøÅåΔ_ΦΓΛΩΠΨΣΘΞÆæßÉ !"#¤%&''()*+,-./0123456789:;<=>?¡ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÑÜ§¿abcdefghijklmnopqrstuvwxyzäöñüà^{}\[~]|€'
                     || chr(10) || chr(13), '') = ''
$$;

ALTER TABLE comms.template
  ADD COLUMN subject text,
  ADD CONSTRAINT template_email_subject CHECK (channel <> 'email' OR subject IS NOT NULL),
  ADD CONSTRAINT template_subject_channels CHECK (subject IS NULL OR channel IN ('email', 'push', 'in_app')),
  ADD CONSTRAINT template_sms_gsm7 CHECK (channel <> 'sms' OR comms.is_gsm7(body));

-- An approved template is what people were told: it never changes (a new version does), and a
-- retired one stays retired.
CREATE FUNCTION comms.guard_template() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.status <> 'draft' THEN
      RAISE EXCEPTION 'template %/% v% is %; it is never deleted', OLD.key, OLD.channel, OLD.version, OLD.status
        USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN OLD;
  END IF;
  IF OLD.status = 'retired' THEN
    RAISE EXCEPTION 'retired templates cannot change' USING ERRCODE = 'restrict_violation';
  END IF;
  IF OLD.status = 'approved'
     AND (NEW.status = 'draft'
          OR (NEW.body, NEW.subject, NEW.provider_template_name, NEW.category)
             IS DISTINCT FROM (OLD.body, OLD.subject, OLD.provider_template_name, OLD.category)) THEN
    RAISE EXCEPTION 'approved template %/% v% cannot change; add a new version', OLD.key, OLD.channel, OLD.version
      USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER template_guard BEFORE UPDATE OR DELETE ON comms.template
  FOR EACH ROW EXECUTE FUNCTION comms.guard_template();

-- comms: messages --------------------------------------------------------------------------------------

ALTER TABLE comms.message
  ALTER COLUMN recipient_account_id DROP NOT NULL,
  ADD COLUMN recipient_address text
    CHECK (recipient_address IS NULL OR recipient_address ~ '^\+[1-9][0-9]{6,14}$' OR recipient_address ~ '^[^@\s]+@[^@\s]+$'),
  ADD COLUMN outbox_id       bigint REFERENCES core.outbox (id),
  ADD COLUMN attempts        integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  ADD COLUMN next_attempt_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  ADD COLUMN fallback_due_at timestamptz,
  ADD COLUMN expires_at      timestamptz,      -- no use after this (lot closed, code expired): suppressed, not sent
  ADD COLUMN read_at         timestamptz,
  ADD CONSTRAINT message_recipient CHECK (recipient_account_id IS NOT NULL OR recipient_address IS NOT NULL),
  ADD CONSTRAINT message_sent_has_provider CHECK (status NOT IN ('sent', 'delivered', 'read')
                                                  OR (sent_at IS NOT NULL AND provider IS NOT NULL AND provider_message_id IS NOT NULL)),
  ADD CONSTRAINT message_delivered_at CHECK (status NOT IN ('delivered', 'read') OR delivered_at IS NOT NULL),
  ADD CONSTRAINT message_read_at CHECK ((status = 'read') = (read_at IS NOT NULL)),
  ADD CONSTRAINT message_failure_reason CHECK (status NOT IN ('failed', 'suppressed') OR failure_reason IS NOT NULL),
  ADD CONSTRAINT message_fallback_not_self CHECK (fallback_of IS NULL OR fallback_of <> id);

-- R4 for messages to an address with no account yet (a sign-up code, a reply to an unknown number).
CREATE UNIQUE INDEX message_address_uniq ON comms.message (message_key, channel, recipient_address) WHERE recipient_account_id IS NULL;
-- A provider's id names one message, so a status webhook updates exactly one row.
CREATE UNIQUE INDEX message_provider_uniq ON comms.message (provider, provider_message_id) WHERE provider_message_id IS NOT NULL;
CREATE INDEX message_queued_idx ON comms.message (next_attempt_at) WHERE status = 'queued';
CREATE INDEX message_fallback_due_idx ON comms.message (fallback_due_at) WHERE status = 'sent' AND fallback_due_at IS NOT NULL;
CREATE INDEX message_feed_idx ON comms.message (recipient_account_id, queued_at DESC) WHERE channel = 'in_app';
CREATE INDEX message_fallback_of_idx ON comms.message (fallback_of) WHERE fallback_of IS NOT NULL;

-- Status only moves forward: queued → sent → delivered → read, or to failed / suppressed.
-- Who, what and how never change after queueing. Messages are never deleted.
CREATE FUNCTION comms.guard_message() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_parent comms.message%ROWTYPE;
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'comms.message is a record of what people were told: DELETE is not allowed'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF NEW.fallback_of IS NOT NULL THEN
      SELECT * INTO v_parent FROM comms.message WHERE id = NEW.fallback_of;
      IF v_parent.message_key IS DISTINCT FROM NEW.message_key
         OR v_parent.recipient_account_id IS DISTINCT FROM NEW.recipient_account_id
         OR v_parent.recipient_address IS DISTINCT FROM NEW.recipient_address
         OR v_parent.channel = NEW.channel THEN
        RAISE EXCEPTION 'a fallback is the same message to the same person on another channel'
          USING ERRCODE = 'check_violation';
      END IF;
    END IF;
    RETURN NEW;
  END IF;
  IF (NEW.message_key, NEW.recipient_account_id, NEW.recipient_address, NEW.channel, NEW.template_key,
      NEW.template_version, NEW.locale, NEW.fallback_of, NEW.queued_at, NEW.outbox_id, NEW.expires_at)
     IS DISTINCT FROM
     (OLD.message_key, OLD.recipient_account_id, OLD.recipient_address, OLD.channel, OLD.template_key,
      OLD.template_version, OLD.locale, OLD.fallback_of, OLD.queued_at, OLD.outbox_id, OLD.expires_at) THEN
    RAISE EXCEPTION 'a queued message''s recipient, channel and template cannot change' USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW.status <> OLD.status AND NOT (
       (OLD.status = 'queued'    AND NEW.status IN ('sent', 'delivered', 'read', 'failed', 'suppressed'))
    OR (OLD.status = 'sent'      AND NEW.status IN ('delivered', 'read', 'failed'))
    OR (OLD.status = 'delivered' AND NEW.status = 'read')) THEN
    RAISE EXCEPTION 'message status cannot go from % to %', OLD.status, NEW.status USING ERRCODE = 'check_violation';
  END IF;
  IF OLD.provider_message_id IS NOT NULL AND NEW.provider_message_id IS DISTINCT FROM OLD.provider_message_id THEN
    RAISE EXCEPTION 'a message''s provider id cannot change' USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW.attempts < OLD.attempts THEN
    RAISE EXCEPTION 'message attempts never go down' USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER message_guard BEFORE INSERT OR UPDATE OR DELETE ON comms.message
  FOR EACH ROW EXECUTE FUNCTION comms.guard_message();
CREATE TRIGGER message_audit AFTER INSERT OR UPDATE ON comms.message
  FOR EACH ROW EXECUTE FUNCTION audit.log_state_change('status');

-- comms: preferences ---------------------------------------------------------------------------------

ALTER TABLE comms.preference
  ADD CONSTRAINT preference_category CHECK (category IN ('outbid', 'ending_soon', 'auction_results', 'payments', 'collection',
                                                         'selling', 'account', 'staff_tasks', 'marketing'));

-- Transactional categories always keep at least one channel (docs/16 §6).
CREATE FUNCTION comms.guard_preference() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT NEW.enabled
     AND NEW.category IN ('auction_results', 'payments', 'collection', 'selling', 'account', 'staff_tasks')
     AND (SELECT count(*) FROM comms.preference
           WHERE account_id = NEW.account_id AND category = NEW.category AND NOT enabled) >= 4 THEN
    RAISE EXCEPTION '% messages need at least one channel', NEW.category USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE CONSTRAINT TRIGGER preference_keeps_a_channel AFTER INSERT OR UPDATE ON comms.preference
  FOR EACH ROW EXECUTE FUNCTION comms.guard_preference();

-- Preference changes are recorded with the category and channel they changed.
CREATE FUNCTION comms.audit_preference() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_actor text := nullif(current_setting('app.actor_type', true), '');
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.enabled = NEW.enabled THEN
    RETURN NEW;
  END IF;
  IF v_actor IS NULL THEN
    RAISE EXCEPTION 'audit actor not set: % on comms.preference must call audit.set_actor() first', TG_OP
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  INSERT INTO audit.event (actor_type, actor_id, actor_name, entity_type, entity_id, action, from_state, to_state, reason, request_id, data)
  VALUES (v_actor, nullif(current_setting('app.actor_id', true), ''), nullif(current_setting('app.actor_name', true), ''),
          'comms.preference', NEW.account_id::text, CASE TG_OP WHEN 'INSERT' THEN 'create' ELSE 'enabled_change' END,
          CASE TG_OP WHEN 'UPDATE' THEN OLD.enabled::text END, NEW.enabled::text,
          nullif(current_setting('app.reason', true), ''), nullif(current_setting('app.request_id', true), ''),
          jsonb_build_object('category', NEW.category, 'channel', NEW.channel));
  RETURN NEW;
END $$;

CREATE TRIGGER preference_audit AFTER INSERT OR UPDATE ON comms.preference
  FOR EACH ROW EXECUTE FUNCTION comms.audit_preference();

-- comms: inbound messages and chat conversations ---------------------------------------------------------

-- Each inbound provider message is handled once, however often the provider retries the webhook.
-- Only ids and kind are kept; the text lives in the conversation state while it is needed.
CREATE TABLE comms.inbound_message (
  provider            text NOT NULL,
  provider_message_id text NOT NULL,
  from_address        text NOT NULL CHECK (from_address ~ '^\+[1-9][0-9]{6,14}$'),
  kind                text NOT NULL CHECK (kind IN ('text', 'image', 'other')),
  received_at         timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (provider, provider_message_id)
);

CREATE TRIGGER inbound_message_append_only BEFORE UPDATE OR DELETE ON comms.inbound_message
  FOR EACH ROW EXECUTE FUNCTION audit.forbid_mutation();

-- A chat flow's state between messages (seller intake over WhatsApp, packages/seller).
CREATE TABLE comms.conversation (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  channel        text NOT NULL CHECK (channel IN ('whatsapp')),
  address        text NOT NULL CHECK (address ~ '^\+[1-9][0-9]{6,14}$'),
  account_id     uuid NOT NULL REFERENCES identity.account (id),
  flow           text NOT NULL CHECK (flow IN ('seller_intake')),
  step           text NOT NULL CHECK (step IN ('category', 'title', 'condition', 'photos', 'reserve', 'confirm',
                                                'submitting', 'done', 'cancelled')),
  state          jsonb NOT NULL,
  consignment_id uuid REFERENCES seller.consignment (id),
  lot_id         uuid REFERENCES catalogue.lot (id),
  started_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
  ended_at       timestamptz,
  CHECK ((step IN ('done', 'cancelled')) = (ended_at IS NOT NULL)),
  CHECK (step <> 'done' OR (consignment_id IS NOT NULL AND lot_id IS NOT NULL))
);
-- One open conversation per chat.
CREATE UNIQUE INDEX conversation_open_uniq ON comms.conversation (channel, address) WHERE ended_at IS NULL;

CREATE TRIGGER conversation_audit AFTER INSERT OR UPDATE ON comms.conversation
  FOR EACH ROW EXECUTE FUNCTION audit.log_state_change('step');

-- comms: the seeded template library (same rows as db/seed.sql) -------------------------------------
-- BEGIN comms template library (generated: pnpm --filter @abc/comms templates:sql)
INSERT INTO comms.template (key, version, channel, locale, category, subject, body, provider_template_name, status) VALUES
  ('outbid', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: You were outbid on {{lot}}. It is now {{price}}. Bid again: {{link}}', 'abc_outbid_v1', 'approved'),
  ('outbid', 1, 'push', 'en-ZW', 'alert', 'You have been outbid on {{lot}}', 'ABC Auctions: You were outbid on {{lot}}. It is now {{price}}. Bid again: {{link}}', NULL, 'approved'),
  ('outbid', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: You were outbid on {{lot}}. It is now {{price}}. Bid again: {{link}}', NULL, 'approved'),
  ('outbid', 1, 'email', 'en-ZW', 'alert', 'You have been outbid on {{lot}}', E'You are no longer the highest bidder on {{lot}}. The current price is {{price}}.\n\nTo bid again, open {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('outbid', 1, 'in_app', 'en-ZW', 'alert', 'You have been outbid on {{lot}}', 'ABC Auctions: You were outbid on {{lot}}. It is now {{price}}. Bid again: {{link}}', NULL, 'approved'),
  ('ending_soon_leading', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. You are leading at {{price}}. {{link}}', 'abc_ending_soon_leading_v1', 'approved'),
  ('ending_soon_leading', 1, 'push', 'en-ZW', 'alert', '{{lot}} closes soon: you are leading', 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. You are leading at {{price}}. {{link}}', NULL, 'approved'),
  ('ending_soon_leading', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. You are leading at {{price}}. {{link}}', NULL, 'approved'),
  ('ending_soon_leading', 1, 'email', 'en-ZW', 'alert', '{{lot}} closes soon: you are leading', E'{{lot}} closes in {{minutes}} minutes. You are the highest bidder at {{price}}.\n\nWatch it close: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('ending_soon_leading', 1, 'in_app', 'en-ZW', 'alert', '{{lot}} closes soon: you are leading', 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. You are leading at {{price}}. {{link}}', NULL, 'approved'),
  ('ending_soon_watching', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. Price {{price}}; you are not leading. {{link}}', 'abc_ending_soon_watching_v1', 'approved'),
  ('ending_soon_watching', 1, 'push', 'en-ZW', 'alert', '{{lot}} closes soon', 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. Price {{price}}; you are not leading. {{link}}', NULL, 'approved'),
  ('ending_soon_watching', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. Price {{price}}; you are not leading. {{link}}', NULL, 'approved'),
  ('ending_soon_watching', 1, 'email', 'en-ZW', 'alert', '{{lot}} closes soon', E'{{lot}} closes in {{minutes}} minutes. The price is {{price}} and you are not the highest bidder.\n\nTo bid, open {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('ending_soon_watching', 1, 'in_app', 'en-ZW', 'alert', '{{lot}} closes soon', 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. Price {{price}}; you are not leading. {{link}}', NULL, 'approved'),
  ('won', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: You won {{lot}} for {{price}}. Your invoice follows when the auction closes. {{link}}', 'abc_won_v1', 'approved'),
  ('won', 1, 'push', 'en-ZW', 'transactional', 'You won {{lot}}', 'ABC Auctions: You won {{lot}} for {{price}}. Your invoice follows when the auction closes. {{link}}', NULL, 'approved'),
  ('won', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: You won {{lot}} for {{price}}. Your invoice follows when the auction closes. {{link}}', NULL, 'approved'),
  ('won', 1, 'email', 'en-ZW', 'transactional', 'You won {{lot}}', E'You won {{lot}} with a hammer price of {{price}}.\n\nWe will send your invoice, with fees and taxes, when the whole auction has closed. You can see the lot at {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('won', 1, 'in_app', 'en-ZW', 'transactional', 'You won {{lot}}', 'ABC Auctions: You won {{lot}} for {{price}}. Your invoice follows when the auction closes. {{link}}', NULL, 'approved'),
  ('lost', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: Bidding has ended on {{lot}} and your bid did not win. See other lots: {{link}}', 'abc_lost_v1', 'approved'),
  ('lost', 1, 'push', 'en-ZW', 'alert', 'Bidding has ended on {{lot}}', 'ABC Auctions: Bidding has ended on {{lot}} and your bid did not win. See other lots: {{link}}', NULL, 'approved'),
  ('lost', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: Bidding has ended on {{lot}} and your bid did not win. See other lots: {{link}}', NULL, 'approved'),
  ('lost', 1, 'email', 'en-ZW', 'alert', 'Bidding has ended on {{lot}}', E'Bidding has ended on {{lot}} and your bid did not win. Any deposit for this auction is released when the auction is settled.\n\nSee other lots: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('lost', 1, 'in_app', 'en-ZW', 'alert', 'Bidding has ended on {{lot}}', 'ABC Auctions: Bidding has ended on {{lot}} and your bid did not win. See other lots: {{link}}', NULL, 'approved'),
  ('invoice_issued', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} for {{total}} is ready. Please pay by {{due}}: {{link}}', 'abc_invoice_issued_v1', 'approved'),
  ('invoice_issued', 1, 'push', 'en-ZW', 'transactional', 'Invoice {{invoice}}: please pay by {{due}}', 'ABC Auctions: Invoice {{invoice}} for {{total}} is ready. Please pay by {{due}}: {{link}}', NULL, 'approved'),
  ('invoice_issued', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} for {{total}} is ready. Please pay by {{due}}: {{link}}', NULL, 'approved'),
  ('invoice_issued', 1, 'email', 'en-ZW', 'transactional', 'Invoice {{invoice}}: please pay by {{due}}', E'Your invoice {{invoice}} for {{total}} is ready. It shows every fee and tax.\n\nPlease pay by {{due}}. You can pay from your wallet or by mobile money in the app: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('invoice_issued', 1, 'in_app', 'en-ZW', 'transactional', 'Invoice {{invoice}}: please pay by {{due}}', 'ABC Auctions: Invoice {{invoice}} for {{total}} is ready. Please pay by {{due}}: {{link}}', NULL, 'approved'),
  ('payment_reminder', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions reminder: Invoice {{invoice}} for {{total}} is due by {{due}}. Pay here: {{link}}', 'abc_payment_reminder_v1', 'approved'),
  ('payment_reminder', 1, 'push', 'en-ZW', 'transactional', 'Reminder: invoice {{invoice}} is due by {{due}}', 'ABC Auctions reminder: Invoice {{invoice}} for {{total}} is due by {{due}}. Pay here: {{link}}', NULL, 'approved'),
  ('payment_reminder', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions reminder: Invoice {{invoice}} for {{total}} is due by {{due}}. Pay here: {{link}}', NULL, 'approved'),
  ('payment_reminder', 1, 'email', 'en-ZW', 'transactional', 'Reminder: invoice {{invoice}} is due by {{due}}', E'This is a reminder that invoice {{invoice}} for {{total}} is due by {{due}}.\n\nPay in the app: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payment_reminder', 1, 'in_app', 'en-ZW', 'transactional', 'Reminder: invoice {{invoice}} is due by {{due}}', 'ABC Auctions reminder: Invoice {{invoice}} for {{total}} is due by {{due}}. Pay here: {{link}}', NULL, 'approved'),
  ('payment_reminder_final', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions final reminder: pay {{invoice}} ({{total}}) by {{due}} to keep your deposit. {{link}}', 'abc_payment_reminder_final_v1', 'approved'),
  ('payment_reminder_final', 1, 'push', 'en-ZW', 'transactional', 'Final reminder: invoice {{invoice}} is due by {{due}}', 'ABC Auctions final reminder: pay {{invoice}} ({{total}}) by {{due}} to keep your deposit. {{link}}', NULL, 'approved'),
  ('payment_reminder_final', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions final reminder: pay {{invoice}} ({{total}}) by {{due}} to keep your deposit. {{link}}', NULL, 'approved'),
  ('payment_reminder_final', 1, 'email', 'en-ZW', 'transactional', 'Final reminder: invoice {{invoice}} is due by {{due}}', E'Invoice {{invoice}} for {{total}} is due by {{due}}.\n\nIf it is not paid by then, your deposit for this auction may be forfeited and a relisting fee charged, as set out in the rules. Pay in the app: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payment_reminder_final', 1, 'in_app', 'en-ZW', 'transactional', 'Final reminder: invoice {{invoice}} is due by {{due}}', 'ABC Auctions final reminder: pay {{invoice}} ({{total}}) by {{due}} to keep your deposit. {{link}}', NULL, 'approved'),
  ('payment_received', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have received {{amount}} for invoice {{invoice}}. Thank you.', 'abc_payment_received_v1', 'approved'),
  ('payment_received', 1, 'push', 'en-ZW', 'transactional', 'Payment received for invoice {{invoice}}', 'ABC Auctions: We have received {{amount}} for invoice {{invoice}}. Thank you.', NULL, 'approved'),
  ('payment_received', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have received {{amount}} for invoice {{invoice}}. Thank you.', NULL, 'approved'),
  ('payment_received', 1, 'email', 'en-ZW', 'transactional', 'Payment received for invoice {{invoice}}', E'We have received your payment of {{amount}} for invoice {{invoice}}. Thank you.\n\nWe will tell you when your goods are ready to collect.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payment_received', 1, 'in_app', 'en-ZW', 'transactional', 'Payment received for invoice {{invoice}}', 'ABC Auctions: We have received {{amount}} for invoice {{invoice}}. Thank you.', NULL, 'approved'),
  ('gate_pass_ready', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Gate pass for {{invoice}} is in the app. Collect in {{branch}} by {{collectBy}}. {{link}}', 'abc_gate_pass_ready_v1', 'approved'),
  ('gate_pass_ready', 1, 'push', 'en-ZW', 'transactional', 'Ready to collect: invoice {{invoice}}', 'ABC Auctions: Gate pass for {{invoice}} is in the app. Collect in {{branch}} by {{collectBy}}. {{link}}', NULL, 'approved'),
  ('gate_pass_ready', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Gate pass for {{invoice}} is in the app. Collect in {{branch}} by {{collectBy}}. {{link}}', NULL, 'approved'),
  ('gate_pass_ready', 1, 'email', 'en-ZW', 'transactional', 'Ready to collect: invoice {{invoice}}', E'Your goods for invoice {{invoice}} are ready. Show the gate pass in the app at our {{branch}} branch and collect by {{collectBy}}.\n\nOpen the gate pass: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('gate_pass_ready', 1, 'in_app', 'en-ZW', 'transactional', 'Ready to collect: invoice {{invoice}}', 'ABC Auctions: Gate pass for {{invoice}} is in the app. Collect in {{branch}} by {{collectBy}}. {{link}}', NULL, 'approved'),
  ('default_warning', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} for {{total}} is overdue. Pay now to keep your deposit: {{link}}', 'abc_default_warning_v1', 'approved'),
  ('default_warning', 1, 'push', 'en-ZW', 'transactional', 'Invoice {{invoice}} is overdue', 'ABC Auctions: Invoice {{invoice}} for {{total}} is overdue. Pay now to keep your deposit: {{link}}', NULL, 'approved'),
  ('default_warning', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} for {{total}} is overdue. Pay now to keep your deposit: {{link}}', NULL, 'approved'),
  ('default_warning', 1, 'email', 'en-ZW', 'transactional', 'Invoice {{invoice}} is overdue', E'Invoice {{invoice}} for {{total}} was not paid in time.\n\nPlease pay now. If it stays unpaid, your deposit for this auction is forfeited and the lots are offered again, as set out in the rules. Pay in the app: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('default_warning', 1, 'in_app', 'en-ZW', 'transactional', 'Invoice {{invoice}} is overdue', 'ABC Auctions: Invoice {{invoice}} for {{total}} is overdue. Pay now to keep your deposit: {{link}}', NULL, 'approved'),
  ('deposit_forfeited', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} was not paid in time. It is cancelled and your deposit of {{deposit}} is forfeited.', 'abc_deposit_forfeited_v1', 'approved'),
  ('deposit_forfeited', 1, 'push', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled; deposit forfeited', 'ABC Auctions: Invoice {{invoice}} was not paid in time. It is cancelled and your deposit of {{deposit}} is forfeited.', NULL, 'approved'),
  ('deposit_forfeited', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} was not paid in time. It is cancelled and your deposit of {{deposit}} is forfeited.', NULL, 'approved'),
  ('deposit_forfeited', 1, 'email', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled; deposit forfeited', E'Invoice {{invoice}} was not paid in time, so it is cancelled and the lots will be offered again.\n\nYour deposit of {{deposit}} for this auction is forfeited, as set out in the rules.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('deposit_forfeited', 1, 'in_app', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled; deposit forfeited', 'ABC Auctions: Invoice {{invoice}} was not paid in time. It is cancelled and your deposit of {{deposit}} is forfeited.', NULL, 'approved'),
  ('invoice_cancelled', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} was not paid in time and is cancelled. The lots will be offered again.', 'abc_invoice_cancelled_v1', 'approved'),
  ('invoice_cancelled', 1, 'push', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled', 'ABC Auctions: Invoice {{invoice}} was not paid in time and is cancelled. The lots will be offered again.', NULL, 'approved'),
  ('invoice_cancelled', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} was not paid in time and is cancelled. The lots will be offered again.', NULL, 'approved'),
  ('invoice_cancelled', 1, 'email', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled', E'Invoice {{invoice}} was not paid in time, so it is cancelled and the lots will be offered again.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('invoice_cancelled', 1, 'in_app', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled', 'ABC Auctions: Invoice {{invoice}} was not paid in time and is cancelled. The lots will be offered again.', NULL, 'approved'),
  ('title_step_overdue', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC staff: {{step}} for {{lot}} was due {{due}} and is not done. Please update the title tracker.', 'abc_title_step_overdue_v1', 'approved'),
  ('title_step_overdue', 1, 'push', 'en-ZW', 'transactional', 'Overdue: {{step}} for {{lot}}', 'ABC staff: {{step}} for {{lot}} was due {{due}} and is not done. Please update the title tracker.', NULL, 'approved'),
  ('title_step_overdue', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC staff: {{step}} for {{lot}} was due {{due}} and is not done. Please update the title tracker.', NULL, 'approved'),
  ('title_step_overdue', 1, 'email', 'en-ZW', 'transactional', 'Overdue: {{step}} for {{lot}}', E'{{step}} for {{lot}} was due {{due}} and is not marked done.\n\nPlease complete it or record why it is delayed in the title tracker. The buyer cannot collect until every step is done.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('title_step_overdue', 1, 'in_app', 'en-ZW', 'transactional', 'Overdue: {{step}} for {{lot}}', 'ABC staff: {{step}} for {{lot}} was due {{due}} and is not done. Please update the title tracker.', NULL, 'approved'),
  ('title_complete', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Papers for {{lot}} are done. Collect it in {{branch}} with your gate pass. {{link}}', 'abc_title_complete_v1', 'approved'),
  ('title_complete', 1, 'push', 'en-ZW', 'transactional', 'Papers complete: {{lot}} is ready to collect', 'ABC Auctions: Papers for {{lot}} are done. Collect it in {{branch}} with your gate pass. {{link}}', NULL, 'approved'),
  ('title_complete', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Papers for {{lot}} are done. Collect it in {{branch}} with your gate pass. {{link}}', NULL, 'approved'),
  ('title_complete', 1, 'email', 'en-ZW', 'transactional', 'Papers complete: {{lot}} is ready to collect', E'Police clearance, ZIMRA clearance and the change of ownership for {{lot}} are complete.\n\nShow your gate pass in the app at our {{branch}} branch to collect it: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('title_complete', 1, 'in_app', 'en-ZW', 'transactional', 'Papers complete: {{lot}} is ready to collect', 'ABC Auctions: Papers for {{lot}} are done. Collect it in {{branch}} with your gate pass. {{link}}', NULL, 'approved'),
  ('payout_scheduled', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: A payout of {{amount}} is scheduled for {{due}}. See your statement in the app.', 'abc_payout_scheduled_v1', 'approved'),
  ('payout_scheduled', 1, 'push', 'en-ZW', 'transactional', 'Payout of {{amount}} scheduled', 'ABC Auctions: A payout of {{amount}} is scheduled for {{due}}. See your statement in the app.', NULL, 'approved'),
  ('payout_scheduled', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: A payout of {{amount}} is scheduled for {{due}}. See your statement in the app.', NULL, 'approved'),
  ('payout_scheduled', 1, 'email', 'en-ZW', 'transactional', 'Payout of {{amount}} scheduled', E'A payout of {{amount}} is scheduled for {{due}}, after the claim window.\n\nYour statement in the app shows each lot, the commission and any deductions.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payout_scheduled', 1, 'in_app', 'en-ZW', 'transactional', 'Payout of {{amount}} scheduled', 'ABC Auctions: A payout of {{amount}} is scheduled for {{due}}. See your statement in the app.', NULL, 'approved'),
  ('payout_paid', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have sent your payout of {{amount}}. Reference {{reference}}.', 'abc_payout_paid_v1', 'approved'),
  ('payout_paid', 1, 'push', 'en-ZW', 'transactional', 'Payout of {{amount}} sent', 'ABC Auctions: We have sent your payout of {{amount}}. Reference {{reference}}.', NULL, 'approved'),
  ('payout_paid', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have sent your payout of {{amount}}. Reference {{reference}}.', NULL, 'approved'),
  ('payout_paid', 1, 'email', 'en-ZW', 'transactional', 'Payout of {{amount}} sent', E'We have sent your payout of {{amount}}. The payment reference is {{reference}}.\n\nIt may take a working day to reach your account.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payout_paid', 1, 'in_app', 'en-ZW', 'transactional', 'Payout of {{amount}} sent', 'ABC Auctions: We have sent your payout of {{amount}}. Reference {{reference}}.', NULL, 'approved'),
  ('payout_blocked', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your payout for invoice {{invoice}} is on hold: {{reason}}. We will tell you when it is released.', 'abc_payout_blocked_v1', 'approved'),
  ('payout_blocked', 1, 'push', 'en-ZW', 'transactional', 'Payout on hold for invoice {{invoice}}', 'ABC Auctions: Your payout for invoice {{invoice}} is on hold: {{reason}}. We will tell you when it is released.', NULL, 'approved'),
  ('payout_blocked', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your payout for invoice {{invoice}} is on hold: {{reason}}. We will tell you when it is released.', NULL, 'approved'),
  ('payout_blocked', 1, 'email', 'en-ZW', 'transactional', 'Payout on hold for invoice {{invoice}}', E'Your payout for the lots on invoice {{invoice}} is on hold: {{reason}}.\n\nNothing is lost. We will tell you as soon as it is released.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payout_blocked', 1, 'in_app', 'en-ZW', 'transactional', 'Payout on hold for invoice {{invoice}}', 'ABC Auctions: Your payout for invoice {{invoice}} is on hold: {{reason}}. We will tell you when it is released.', NULL, 'approved'),
  ('registration_approved', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: You are registered for {{auction}}. You can bid now.', 'abc_registration_approved_v1', 'approved'),
  ('registration_approved', 1, 'push', 'en-ZW', 'transactional', 'You are registered for {{auction}}', 'ABC Auctions: You are registered for {{auction}}. You can bid now.', NULL, 'approved'),
  ('registration_approved', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: You are registered for {{auction}}. You can bid now.', NULL, 'approved'),
  ('registration_approved', 1, 'email', 'en-ZW', 'transactional', 'You are registered for {{auction}}', E'You are registered for {{auction}} and can bid now. Your limit is shown on every lot before you confirm a bid.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('registration_approved', 1, 'in_app', 'en-ZW', 'transactional', 'You are registered for {{auction}}', 'ABC Auctions: You are registered for {{auction}}. You can bid now.', NULL, 'approved'),
  ('registration_review', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your registration for {{auction}} needs a quick check by our team. We will tell you when it is done.', 'abc_registration_review_v1', 'approved'),
  ('registration_review', 1, 'push', 'en-ZW', 'transactional', 'Your registration for {{auction}} is being checked', 'ABC Auctions: Your registration for {{auction}} needs a quick check by our team. We will tell you when it is done.', NULL, 'approved'),
  ('registration_review', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your registration for {{auction}} needs a quick check by our team. We will tell you when it is done.', NULL, 'approved'),
  ('registration_review', 1, 'email', 'en-ZW', 'transactional', 'Your registration for {{auction}} is being checked', E'Your registration for {{auction}} needs a quick check by our team before you can bid. We will tell you when it is done.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('registration_review', 1, 'in_app', 'en-ZW', 'transactional', 'Your registration for {{auction}} is being checked', 'ABC Auctions: Your registration for {{auction}} needs a quick check by our team. We will tell you when it is done.', NULL, 'approved'),
  ('otp_code', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your sign-in code is {{code}}. It expires in {{minutes}} minutes. Do not share it with anyone.', 'abc_otp_code_v1', 'approved'),
  ('otp_code', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your sign-in code is {{code}}. It expires in {{minutes}} minutes. Do not share it with anyone.', NULL, 'approved'),
  ('otp_code', 1, 'email', 'en-ZW', 'transactional', 'Your ABC Auctions sign-in code', E'Your sign-in code is {{code}}. It expires in {{minutes}} minutes.\n\nDo not share it with anyone. ABC staff will never ask for it. If you did not ask for this code, you can ignore this email.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('consignment_received', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have received the details of {{title}} (ref {{ref}}). Our intake team will send your valuation and consignment note.', 'abc_consignment_received_v1', 'approved'),
  ('consignment_received', 1, 'push', 'en-ZW', 'transactional', 'We have received {{title}}', 'ABC Auctions: We have received the details of {{title}} (ref {{ref}}). Our intake team will send your valuation and consignment note.', NULL, 'approved'),
  ('consignment_received', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have received the details of {{title}} (ref {{ref}}). Our intake team will send your valuation and consignment note.', NULL, 'approved'),
  ('consignment_received', 1, 'email', 'en-ZW', 'transactional', 'We have received {{title}}', E'We have received the details of {{title}} (reference {{ref}}).\n\nOur intake team will check them and send you a valuation range and your consignment note to sign in the app.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('consignment_received', 1, 'in_app', 'en-ZW', 'transactional', 'We have received {{title}}', 'ABC Auctions: We have received the details of {{title}} (ref {{ref}}). Our intake team will send your valuation and consignment note.', NULL, 'approved'),
  ('chat_reply', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, '{{text}}', NULL, 'approved')
ON CONFLICT (key, version, channel, locale) DO NOTHING;
-- END comms template library
