-- Watch list and saved searches with alerts (catalogue, docs/05 §7; messages, docs/16 §4).
-- Folded into db/schema.sql and db/seed.sql as well; this file brings existing
-- databases up to date. No BEGIN/COMMIT: the migration runner wraps it in one transaction.

-- A lot someone saved for later. Personal and reversible, so not audited; the
-- ending-soon alert goes to watchers as well as bidders.
CREATE TABLE catalogue.watch (
  account_id uuid NOT NULL REFERENCES identity.account (id),
  lot_id     uuid NOT NULL REFERENCES catalogue.lot (id),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (account_id, lot_id)
);
CREATE INDEX watch_lot_idx ON catalogue.watch (lot_id);

-- Saved searches (the table predates this migration): one name per person, and the lots
-- each search has already told its owner about, so an alert only ever names new lots.
CREATE INDEX saved_search_account_idx ON catalogue.saved_search (account_id);
ALTER TABLE catalogue.saved_search ADD CONSTRAINT saved_search_name_unique UNIQUE (account_id, name);
CREATE TABLE catalogue.saved_search_hit (
  saved_search_id uuid NOT NULL REFERENCES catalogue.saved_search (id) ON DELETE CASCADE,
  lot_id          uuid NOT NULL REFERENCES catalogue.lot (id),
  seen_at         timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (saved_search_id, lot_id)
);

-- A preference category for saved-search alerts (default: app notification and email,
-- rule comms.preference_defaults).
ALTER TABLE comms.preference DROP CONSTRAINT preference_category;
ALTER TABLE comms.preference ADD CONSTRAINT preference_category CHECK (category IN ('outbid', 'ending_soon', 'saved_searches',
  'auction_results', 'payments', 'collection', 'selling', 'account', 'staff_tasks', 'marketing'));

-- The two new templates (ending_soon_saved, saved_search_match); existing rows are left as they are.

-- BEGIN comms template library (generated: pnpm --filter @abc/comms templates:sql)
INSERT INTO comms.template (key, version, channel, locale, category, subject, body, provider_template_name, status) VALUES
  ('outbid', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: You were outbid on {{lot}}. It is now {{price}}. Bid again: {{link}}', 'abc_outbid_v1', 'approved'),
  ('outbid', 1, 'push', 'en-ZW', 'alert', 'You have been outbid on {{lot}}', 'ABC Auctions: You were outbid on {{lot}}. It is now {{price}}. Bid again: {{link}}', NULL, 'approved'),
  ('outbid', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: You were outbid on {{lot}}. It is now {{price}}. Bid again: {{link}}', NULL, 'approved'),
  ('outbid', 1, 'email', 'en-ZW', 'alert', 'You have been outbid on {{lot}}', E'You are no longer the highest bidder on {{lot}}. The current price is {{price}}.\n\nTo bid again, open {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('outbid', 1, 'in_app', 'en-ZW', 'alert', 'You have been outbid on {{lot}}', 'ABC Auctions: You were outbid on {{lot}}. It is now {{price}}. Bid again: {{link}}', NULL, 'approved'),
  ('ending_soon_leading', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. You are leading at {{price}}. {{link}}', 'abc_ending_soon_leading_v1', 'approved'),
  ('ending_soon_leading', 1, 'push', 'en-ZW', 'alert', '{{lot}} closes soon: you are leading', 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. You are leading at {{price}}. {{link}}', NULL, 'approved'),
  ('ending_soon_leading', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. You are leading at {{price}}. {{link}}', NULL, 'approved'),
  ('ending_soon_leading', 1, 'email', 'en-ZW', 'alert', '{{lot}} closes soon: you are leading', E'{{lot}} closes in {{minutes}} minutes. You are the highest bidder at {{price}}.\n\nWatch it close: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('ending_soon_leading', 1, 'in_app', 'en-ZW', 'alert', '{{lot}} closes soon: you are leading', 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. You are leading at {{price}}. {{link}}', NULL, 'approved'),
  ('ending_soon_watching', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. Price {{price}}; you are not leading. {{link}}', 'abc_ending_soon_watching_v1', 'approved'),
  ('ending_soon_watching', 1, 'push', 'en-ZW', 'alert', '{{lot}} closes soon', 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. Price {{price}}; you are not leading. {{link}}', NULL, 'approved'),
  ('ending_soon_watching', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. Price {{price}}; you are not leading. {{link}}', NULL, 'approved'),
  ('ending_soon_watching', 1, 'email', 'en-ZW', 'alert', '{{lot}} closes soon', E'{{lot}} closes in {{minutes}} minutes. The price is {{price}} and you are not the highest bidder.\n\nTo bid, open {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('ending_soon_watching', 1, 'in_app', 'en-ZW', 'alert', '{{lot}} closes soon', 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. Price {{price}}; you are not leading. {{link}}', NULL, 'approved'),
  ('ending_soon_saved', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}}, on your watch list, closes in {{minutes}} minutes at {{price}}. {{link}}', 'abc_ending_soon_saved_v1', 'approved'),
  ('ending_soon_saved', 1, 'push', 'en-ZW', 'alert', '{{lot}} on your watch list closes soon', 'ABC Auctions: {{lot}}, on your watch list, closes in {{minutes}} minutes at {{price}}. {{link}}', NULL, 'approved'),
  ('ending_soon_saved', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{lot}}, on your watch list, closes in {{minutes}} minutes at {{price}}. {{link}}', NULL, 'approved'),
  ('ending_soon_saved', 1, 'email', 'en-ZW', 'alert', '{{lot}} on your watch list closes soon', E'{{lot}}, which you saved to your watch list, closes in {{minutes}} minutes. The price is {{price}}.\n\nTo bid, open {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('ending_soon_saved', 1, 'in_app', 'en-ZW', 'alert', '{{lot}} on your watch list closes soon', 'ABC Auctions: {{lot}}, on your watch list, closes in {{minutes}} minutes at {{price}}. {{link}}', NULL, 'approved'),
  ('saved_search_match', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{matches}} for "{{search}}": {{lot}} from {{price}}. {{link}}', 'abc_saved_search_match_v1', 'approved'),
  ('saved_search_match', 1, 'push', 'en-ZW', 'alert', '{{matches}} for "{{search}}"', 'ABC Auctions: {{matches}} for "{{search}}": {{lot}} from {{price}}. {{link}}', NULL, 'approved'),
  ('saved_search_match', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: {{matches}} for "{{search}}": {{lot}} from {{price}}. {{link}}', NULL, 'approved'),
  ('saved_search_match', 1, 'email', 'en-ZW', 'alert', '{{matches}} for "{{search}}"', E'{{matches}} for your saved search "{{search}}", starting with {{lot}} from {{price}}.\n\nSee them all: {{link}}\n\nTo stop these alerts, switch them off on the search in your account.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('saved_search_match', 1, 'in_app', 'en-ZW', 'alert', '{{matches}} for "{{search}}"', 'ABC Auctions: {{matches}} for "{{search}}": {{lot}} from {{price}}. {{link}}', NULL, 'approved'),
  ('won', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: You won {{lot}} for {{price}}. Your invoice follows when the auction closes. {{link}}', 'abc_won_v1', 'approved'),
  ('won', 1, 'push', 'en-ZW', 'transactional', 'You won {{lot}}', 'ABC Auctions: You won {{lot}} for {{price}}. Your invoice follows when the auction closes. {{link}}', NULL, 'approved'),
  ('won', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: You won {{lot}} for {{price}}. Your invoice follows when the auction closes. {{link}}', NULL, 'approved'),
  ('won', 1, 'email', 'en-ZW', 'transactional', 'You won {{lot}}', E'You won {{lot}} with a hammer price of {{price}}.\n\nWe will send your invoice, with fees and taxes, when the whole auction has closed. You can see the lot at {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('won', 1, 'in_app', 'en-ZW', 'transactional', 'You won {{lot}}', 'ABC Auctions: You won {{lot}} for {{price}}. Your invoice follows when the auction closes. {{link}}', NULL, 'approved'),
  ('lost', 1, 'whatsapp', 'en-ZW', 'alert', NULL, 'ABC Auctions: Bidding has ended on {{lot}} and your bid did not win. See other lots: {{link}}', 'abc_lost_v1', 'approved'),
  ('lost', 1, 'push', 'en-ZW', 'alert', 'Bidding has ended on {{lot}}', 'ABC Auctions: Bidding has ended on {{lot}} and your bid did not win. See other lots: {{link}}', NULL, 'approved'),
  ('lost', 1, 'sms', 'en-ZW', 'alert', NULL, 'ABC Auctions: Bidding has ended on {{lot}} and your bid did not win. See other lots: {{link}}', NULL, 'approved'),
  ('lost', 1, 'email', 'en-ZW', 'alert', 'Bidding has ended on {{lot}}', E'Bidding has ended on {{lot}} and your bid did not win. Any deposit for this auction is released when the auction is settled.\n\nSee other lots: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('lost', 1, 'in_app', 'en-ZW', 'alert', 'Bidding has ended on {{lot}}', 'ABC Auctions: Bidding has ended on {{lot}} and your bid did not win. See other lots: {{link}}', NULL, 'approved'),
  ('invoice_issued', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} for {{total}} is ready. Please pay by {{due}}: {{link}}', 'abc_invoice_issued_v1', 'approved'),
  ('invoice_issued', 1, 'push', 'en-ZW', 'transactional', 'Invoice {{invoice}}: please pay by {{due}}', 'ABC Auctions: Invoice {{invoice}} for {{total}} is ready. Please pay by {{due}}: {{link}}', NULL, 'approved'),
  ('invoice_issued', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} for {{total}} is ready. Please pay by {{due}}: {{link}}', NULL, 'approved'),
  ('invoice_issued', 1, 'email', 'en-ZW', 'transactional', 'Invoice {{invoice}}: please pay by {{due}}', E'Your invoice {{invoice}} for {{total}} is ready. It shows every fee and tax.\n\nPlease pay by {{due}}. You can pay from your wallet or by mobile money in the app: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('invoice_issued', 1, 'in_app', 'en-ZW', 'transactional', 'Invoice {{invoice}}: please pay by {{due}}', 'ABC Auctions: Invoice {{invoice}} for {{total}} is ready. Please pay by {{due}}: {{link}}', NULL, 'approved'),
  ('payment_reminder', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions reminder: Invoice {{invoice}} for {{total}} is due by {{due}}. Pay here: {{link}}', 'abc_payment_reminder_v1', 'approved'),
  ('payment_reminder', 1, 'push', 'en-ZW', 'transactional', 'Reminder: invoice {{invoice}} is due by {{due}}', 'ABC Auctions reminder: Invoice {{invoice}} for {{total}} is due by {{due}}. Pay here: {{link}}', NULL, 'approved'),
  ('payment_reminder', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions reminder: Invoice {{invoice}} for {{total}} is due by {{due}}. Pay here: {{link}}', NULL, 'approved'),
  ('payment_reminder', 1, 'email', 'en-ZW', 'transactional', 'Reminder: invoice {{invoice}} is due by {{due}}', E'This is a reminder that invoice {{invoice}} for {{total}} is due by {{due}}.\n\nPay in the app: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payment_reminder', 1, 'in_app', 'en-ZW', 'transactional', 'Reminder: invoice {{invoice}} is due by {{due}}', 'ABC Auctions reminder: Invoice {{invoice}} for {{total}} is due by {{due}}. Pay here: {{link}}', NULL, 'approved'),
  ('payment_reminder_final', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions final reminder: pay {{invoice}} ({{total}}) by {{due}} to keep your deposit. {{link}}', 'abc_payment_reminder_final_v1', 'approved'),
  ('payment_reminder_final', 1, 'push', 'en-ZW', 'transactional', 'Final reminder: invoice {{invoice}} is due by {{due}}', 'ABC Auctions final reminder: pay {{invoice}} ({{total}}) by {{due}} to keep your deposit. {{link}}', NULL, 'approved'),
  ('payment_reminder_final', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions final reminder: pay {{invoice}} ({{total}}) by {{due}} to keep your deposit. {{link}}', NULL, 'approved'),
  ('payment_reminder_final', 1, 'email', 'en-ZW', 'transactional', 'Final reminder: invoice {{invoice}} is due by {{due}}', E'Invoice {{invoice}} for {{total}} is due by {{due}}.\n\nIf it is not paid by then, your deposit for this auction may be forfeited and a relisting fee charged, as set out in the rules. Pay in the app: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payment_reminder_final', 1, 'in_app', 'en-ZW', 'transactional', 'Final reminder: invoice {{invoice}} is due by {{due}}', 'ABC Auctions final reminder: pay {{invoice}} ({{total}}) by {{due}} to keep your deposit. {{link}}', NULL, 'approved'),
  ('payment_received', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have received {{amount}} for invoice {{invoice}}. Thank you.', 'abc_payment_received_v1', 'approved'),
  ('payment_received', 1, 'push', 'en-ZW', 'transactional', 'Payment received for invoice {{invoice}}', 'ABC Auctions: We have received {{amount}} for invoice {{invoice}}. Thank you.', NULL, 'approved'),
  ('payment_received', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have received {{amount}} for invoice {{invoice}}. Thank you.', NULL, 'approved'),
  ('payment_received', 1, 'email', 'en-ZW', 'transactional', 'Payment received for invoice {{invoice}}', E'We have received your payment of {{amount}} for invoice {{invoice}}. Thank you.\n\nWe will tell you when your goods are ready to collect.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payment_received', 1, 'in_app', 'en-ZW', 'transactional', 'Payment received for invoice {{invoice}}', 'ABC Auctions: We have received {{amount}} for invoice {{invoice}}. Thank you.', NULL, 'approved'),
  ('gate_pass_ready', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Gate pass for {{invoice}} is in the app. Collect in {{branch}} by {{collectBy}}. {{link}}', 'abc_gate_pass_ready_v1', 'approved'),
  ('gate_pass_ready', 1, 'push', 'en-ZW', 'transactional', 'Ready to collect: invoice {{invoice}}', 'ABC Auctions: Gate pass for {{invoice}} is in the app. Collect in {{branch}} by {{collectBy}}. {{link}}', NULL, 'approved'),
  ('gate_pass_ready', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Gate pass for {{invoice}} is in the app. Collect in {{branch}} by {{collectBy}}. {{link}}', NULL, 'approved'),
  ('gate_pass_ready', 1, 'email', 'en-ZW', 'transactional', 'Ready to collect: invoice {{invoice}}', E'Your goods for invoice {{invoice}} are ready. Show the gate pass in the app at our {{branch}} branch and collect by {{collectBy}}.\n\nOpen the gate pass: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('gate_pass_ready', 1, 'in_app', 'en-ZW', 'transactional', 'Ready to collect: invoice {{invoice}}', 'ABC Auctions: Gate pass for {{invoice}} is in the app. Collect in {{branch}} by {{collectBy}}. {{link}}', NULL, 'approved'),
  ('default_warning', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} for {{total}} is overdue. Pay now to keep your deposit: {{link}}', 'abc_default_warning_v1', 'approved'),
  ('default_warning', 1, 'push', 'en-ZW', 'transactional', 'Invoice {{invoice}} is overdue', 'ABC Auctions: Invoice {{invoice}} for {{total}} is overdue. Pay now to keep your deposit: {{link}}', NULL, 'approved'),
  ('default_warning', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} for {{total}} is overdue. Pay now to keep your deposit: {{link}}', NULL, 'approved'),
  ('default_warning', 1, 'email', 'en-ZW', 'transactional', 'Invoice {{invoice}} is overdue', E'Invoice {{invoice}} for {{total}} was not paid in time.\n\nPlease pay now. If it stays unpaid, your deposit for this auction is forfeited and the lots are offered again, as set out in the rules. Pay in the app: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('default_warning', 1, 'in_app', 'en-ZW', 'transactional', 'Invoice {{invoice}} is overdue', 'ABC Auctions: Invoice {{invoice}} for {{total}} is overdue. Pay now to keep your deposit: {{link}}', NULL, 'approved'),
  ('deposit_forfeited', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} was not paid in time. It is cancelled and your deposit of {{deposit}} is forfeited.', 'abc_deposit_forfeited_v1', 'approved'),
  ('deposit_forfeited', 1, 'push', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled; deposit forfeited', 'ABC Auctions: Invoice {{invoice}} was not paid in time. It is cancelled and your deposit of {{deposit}} is forfeited.', NULL, 'approved'),
  ('deposit_forfeited', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} was not paid in time. It is cancelled and your deposit of {{deposit}} is forfeited.', NULL, 'approved'),
  ('deposit_forfeited', 1, 'email', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled; deposit forfeited', E'Invoice {{invoice}} was not paid in time, so it is cancelled and the lots will be offered again.\n\nYour deposit of {{deposit}} for this auction is forfeited, as set out in the rules.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('deposit_forfeited', 1, 'in_app', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled; deposit forfeited', 'ABC Auctions: Invoice {{invoice}} was not paid in time. It is cancelled and your deposit of {{deposit}} is forfeited.', NULL, 'approved'),
  ('invoice_cancelled', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} was not paid in time and is cancelled. The lots will be offered again.', 'abc_invoice_cancelled_v1', 'approved'),
  ('invoice_cancelled', 1, 'push', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled', 'ABC Auctions: Invoice {{invoice}} was not paid in time and is cancelled. The lots will be offered again.', NULL, 'approved'),
  ('invoice_cancelled', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Invoice {{invoice}} was not paid in time and is cancelled. The lots will be offered again.', NULL, 'approved'),
  ('invoice_cancelled', 1, 'email', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled', E'Invoice {{invoice}} was not paid in time, so it is cancelled and the lots will be offered again.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('invoice_cancelled', 1, 'in_app', 'en-ZW', 'transactional', 'Invoice {{invoice}} cancelled', 'ABC Auctions: Invoice {{invoice}} was not paid in time and is cancelled. The lots will be offered again.', NULL, 'approved'),
  ('title_step_overdue', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC staff: {{step}} for {{lot}} was due {{due}} and is not done. Please update the title tracker.', 'abc_title_step_overdue_v1', 'approved'),
  ('title_step_overdue', 1, 'push', 'en-ZW', 'transactional', 'Overdue: {{step}} for {{lot}}', 'ABC staff: {{step}} for {{lot}} was due {{due}} and is not done. Please update the title tracker.', NULL, 'approved'),
  ('title_step_overdue', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC staff: {{step}} for {{lot}} was due {{due}} and is not done. Please update the title tracker.', NULL, 'approved'),
  ('title_step_overdue', 1, 'email', 'en-ZW', 'transactional', 'Overdue: {{step}} for {{lot}}', E'{{step}} for {{lot}} was due {{due}} and is not marked done.\n\nPlease complete it or record why it is delayed in the title tracker. The buyer cannot collect until every step is done.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('title_step_overdue', 1, 'in_app', 'en-ZW', 'transactional', 'Overdue: {{step}} for {{lot}}', 'ABC staff: {{step}} for {{lot}} was due {{due}} and is not done. Please update the title tracker.', NULL, 'approved'),
  ('title_complete', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Papers for {{lot}} are done. Collect it in {{branch}} with your gate pass. {{link}}', 'abc_title_complete_v1', 'approved'),
  ('title_complete', 1, 'push', 'en-ZW', 'transactional', 'Papers complete: {{lot}} is ready to collect', 'ABC Auctions: Papers for {{lot}} are done. Collect it in {{branch}} with your gate pass. {{link}}', NULL, 'approved'),
  ('title_complete', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Papers for {{lot}} are done. Collect it in {{branch}} with your gate pass. {{link}}', NULL, 'approved'),
  ('title_complete', 1, 'email', 'en-ZW', 'transactional', 'Papers complete: {{lot}} is ready to collect', E'Police clearance, ZIMRA clearance and the change of ownership for {{lot}} are complete.\n\nShow your gate pass in the app at our {{branch}} branch to collect it: {{link}}\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('title_complete', 1, 'in_app', 'en-ZW', 'transactional', 'Papers complete: {{lot}} is ready to collect', 'ABC Auctions: Papers for {{lot}} are done. Collect it in {{branch}} with your gate pass. {{link}}', NULL, 'approved'),
  ('payout_scheduled', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: A payout of {{amount}} is scheduled for {{due}}. See your statement in the app.', 'abc_payout_scheduled_v1', 'approved'),
  ('payout_scheduled', 1, 'push', 'en-ZW', 'transactional', 'Payout of {{amount}} scheduled', 'ABC Auctions: A payout of {{amount}} is scheduled for {{due}}. See your statement in the app.', NULL, 'approved'),
  ('payout_scheduled', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: A payout of {{amount}} is scheduled for {{due}}. See your statement in the app.', NULL, 'approved'),
  ('payout_scheduled', 1, 'email', 'en-ZW', 'transactional', 'Payout of {{amount}} scheduled', E'A payout of {{amount}} is scheduled for {{due}}, after the claim window.\n\nYour statement in the app shows each lot, the commission and any deductions.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payout_scheduled', 1, 'in_app', 'en-ZW', 'transactional', 'Payout of {{amount}} scheduled', 'ABC Auctions: A payout of {{amount}} is scheduled for {{due}}. See your statement in the app.', NULL, 'approved'),
  ('payout_paid', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have sent your payout of {{amount}}. Reference {{reference}}.', 'abc_payout_paid_v1', 'approved'),
  ('payout_paid', 1, 'push', 'en-ZW', 'transactional', 'Payout of {{amount}} sent', 'ABC Auctions: We have sent your payout of {{amount}}. Reference {{reference}}.', NULL, 'approved'),
  ('payout_paid', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have sent your payout of {{amount}}. Reference {{reference}}.', NULL, 'approved'),
  ('payout_paid', 1, 'email', 'en-ZW', 'transactional', 'Payout of {{amount}} sent', E'We have sent your payout of {{amount}}. The payment reference is {{reference}}.\n\nIt may take a working day to reach your account.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payout_paid', 1, 'in_app', 'en-ZW', 'transactional', 'Payout of {{amount}} sent', 'ABC Auctions: We have sent your payout of {{amount}}. Reference {{reference}}.', NULL, 'approved'),
  ('payout_blocked', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your payout for invoice {{invoice}} is on hold: {{reason}}. We will tell you when it is released.', 'abc_payout_blocked_v1', 'approved'),
  ('payout_blocked', 1, 'push', 'en-ZW', 'transactional', 'Payout on hold for invoice {{invoice}}', 'ABC Auctions: Your payout for invoice {{invoice}} is on hold: {{reason}}. We will tell you when it is released.', NULL, 'approved'),
  ('payout_blocked', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your payout for invoice {{invoice}} is on hold: {{reason}}. We will tell you when it is released.', NULL, 'approved'),
  ('payout_blocked', 1, 'email', 'en-ZW', 'transactional', 'Payout on hold for invoice {{invoice}}', E'Your payout for the lots on invoice {{invoice}} is on hold: {{reason}}.\n\nNothing is lost. We will tell you as soon as it is released.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('payout_blocked', 1, 'in_app', 'en-ZW', 'transactional', 'Payout on hold for invoice {{invoice}}', 'ABC Auctions: Your payout for invoice {{invoice}} is on hold: {{reason}}. We will tell you when it is released.', NULL, 'approved'),
  ('registration_approved', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: You are registered for {{auction}}. You can bid now.', 'abc_registration_approved_v1', 'approved'),
  ('registration_approved', 1, 'push', 'en-ZW', 'transactional', 'You are registered for {{auction}}', 'ABC Auctions: You are registered for {{auction}}. You can bid now.', NULL, 'approved'),
  ('registration_approved', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: You are registered for {{auction}}. You can bid now.', NULL, 'approved'),
  ('registration_approved', 1, 'email', 'en-ZW', 'transactional', 'You are registered for {{auction}}', E'You are registered for {{auction}} and can bid now. Your limit is shown on every lot before you confirm a bid.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('registration_approved', 1, 'in_app', 'en-ZW', 'transactional', 'You are registered for {{auction}}', 'ABC Auctions: You are registered for {{auction}}. You can bid now.', NULL, 'approved'),
  ('registration_review', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your registration for {{auction}} needs a quick check by our team. We will tell you when it is done.', 'abc_registration_review_v1', 'approved'),
  ('registration_review', 1, 'push', 'en-ZW', 'transactional', 'Your registration for {{auction}} is being checked', 'ABC Auctions: Your registration for {{auction}} needs a quick check by our team. We will tell you when it is done.', NULL, 'approved'),
  ('registration_review', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your registration for {{auction}} needs a quick check by our team. We will tell you when it is done.', NULL, 'approved'),
  ('registration_review', 1, 'email', 'en-ZW', 'transactional', 'Your registration for {{auction}} is being checked', E'Your registration for {{auction}} needs a quick check by our team before you can bid. We will tell you when it is done.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('registration_review', 1, 'in_app', 'en-ZW', 'transactional', 'Your registration for {{auction}} is being checked', 'ABC Auctions: Your registration for {{auction}} needs a quick check by our team. We will tell you when it is done.', NULL, 'approved'),
  ('otp_code', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your sign-in code is {{code}}. It expires in {{minutes}} minutes. Do not share it with anyone.', 'abc_otp_code_v1', 'approved'),
  ('otp_code', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: Your sign-in code is {{code}}. It expires in {{minutes}} minutes. Do not share it with anyone.', NULL, 'approved'),
  ('otp_code', 1, 'email', 'en-ZW', 'transactional', 'Your ABC Auctions sign-in code', E'Your sign-in code is {{code}}. It expires in {{minutes}} minutes.\n\nDo not share it with anyone. ABC staff will never ask for it. If you did not ask for this code, you can ignore this email.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('consignment_received', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have received the details of {{title}} (ref {{ref}}). Our intake team will send your valuation and consignment note.', 'abc_consignment_received_v1', 'approved'),
  ('consignment_received', 1, 'push', 'en-ZW', 'transactional', 'We have received {{title}}', 'ABC Auctions: We have received the details of {{title}} (ref {{ref}}). Our intake team will send your valuation and consignment note.', NULL, 'approved'),
  ('consignment_received', 1, 'sms', 'en-ZW', 'transactional', NULL, 'ABC Auctions: We have received the details of {{title}} (ref {{ref}}). Our intake team will send your valuation and consignment note.', NULL, 'approved'),
  ('consignment_received', 1, 'email', 'en-ZW', 'transactional', 'We have received {{title}}', E'We have received the details of {{title}} (reference {{ref}}).\n\nOur intake team will check them and send you a valuation range and your consignment note to sign in the app.\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.', NULL, 'approved'),
  ('consignment_received', 1, 'in_app', 'en-ZW', 'transactional', 'We have received {{title}}', 'ABC Auctions: We have received the details of {{title}} (ref {{ref}}). Our intake team will send your valuation and consignment note.', NULL, 'approved'),
  ('chat_reply', 1, 'whatsapp', 'en-ZW', 'transactional', NULL, '{{text}}', NULL, 'approved')
ON CONFLICT (key, version, channel, locale) DO NOTHING;
-- END comms template library
