import type { CommsPolicy, PreferenceCategory } from '@abc/rules';
import { placeholders } from './render';

/**
 * The template library (docs/16 §3): one short, plain message per thing a person
 * should hear about, described the same way on every channel (docs/01 §6.6).
 * `text` is used for WhatsApp, SMS, app notifications and the in-app feed, so it
 * must fit one SMS (160 GSM characters) with realistic values. Email gets a subject
 * and a slightly longer body. These rows are seeded as `approved` (db/seed.sql and
 * migration 0002, generated by `pnpm --filter @abc/comms templates:sql`).
 *
 * Changing approved copy means adding a new version, never editing one: the
 * database refuses edits to approved templates, because messages already sent
 * point at them.
 */

export const CHANNELS = ['whatsapp', 'push', 'sms', 'email', 'in_app'] as const;
export type Channel = (typeof CHANNELS)[number];

export type TemplateCategory = 'transactional' | 'alert' | 'marketing';

export const DEFAULT_LOCALE = 'en-ZW';

export interface TemplateDefinition {
  key: string;
  version: number;
  category: TemplateCategory;
  /** Preference category people can switch per channel. null: cannot be switched off (sign-in codes, chat replies). */
  preference: PreferenceCategory | null;
  /** Channel order from rule comms.fallback. null: fixed channels (a chat reply stays in the chat). */
  policy: CommsPolicy | null;
  channels: readonly Channel[];
  text: string;
  subject: string;
  email: string;
  /** Realistic values, used in tests (SMS length) and the docs. */
  example: Record<string, string>;
}

const ALL: readonly Channel[] = CHANNELS;

const EMAIL_FOOTER = '\n\nABC Auctions, Harare and Bulawayo.\nChoose which messages you get, and how, in the app under Settings, Messages.';

const LOT = 'Toyota Hilux 2.4 GD-6 Double Cab 2019';
const WEB = 'https://abcauctions.example';
const LINK = `${WEB}/lots/HRE-26-4F2A9C01`;
const INVOICE_LINK = `${WEB}/invoices/HRE-V-2611-0004`;

export const TEMPLATE_LIBRARY: readonly TemplateDefinition[] = [
  {
    key: 'outbid', version: 1, category: 'alert', preference: 'outbid', policy: 'outbid', channels: ALL,
    text: 'ABC Auctions: You were outbid on {{lot}}. It is now {{price}}. Bid again: {{link}}',
    subject: 'You have been outbid on {{lot}}',
    email: 'You are no longer the highest bidder on {{lot}}. The current price is {{price}}.\n\nTo bid again, open {{link}}',
    example: { lot: LOT, price: 'US$24,500.00', link: LINK },
  },
  {
    key: 'ending_soon_leading', version: 1, category: 'alert', preference: 'ending_soon', policy: 'ending_soon', channels: ALL,
    text: 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. You are leading at {{price}}. {{link}}',
    subject: '{{lot}} closes soon: you are leading',
    email: '{{lot}} closes in {{minutes}} minutes. You are the highest bidder at {{price}}.\n\nWatch it close: {{link}}',
    example: { lot: LOT, minutes: '60', price: 'US$24,500.00', link: LINK },
  },
  {
    key: 'ending_soon_watching', version: 1, category: 'alert', preference: 'ending_soon', policy: 'ending_soon', channels: ALL,
    text: 'ABC Auctions: {{lot}} closes in {{minutes}} minutes. Price {{price}}; you are not leading. {{link}}',
    subject: '{{lot}} closes soon',
    email: '{{lot}} closes in {{minutes}} minutes. The price is {{price}} and you are not the highest bidder.\n\nTo bid, open {{link}}',
    example: { lot: LOT, minutes: '60', price: 'US$24,500.00', link: LINK },
  },
  {
    key: 'won', version: 1, category: 'transactional', preference: 'auction_results', policy: 'won', channels: ALL,
    text: 'ABC Auctions: You won {{lot}} for {{price}}. Your invoice follows when the auction closes. {{link}}',
    subject: 'You won {{lot}}',
    email: 'You won {{lot}} with a hammer price of {{price}}.\n\nWe will send your invoice, with fees and taxes, when the whole auction has closed. You can see the lot at {{link}}',
    example: { lot: LOT, price: 'US$24,500.00', link: LINK },
  },
  {
    key: 'lost', version: 1, category: 'alert', preference: 'auction_results', policy: 'lost', channels: ALL,
    text: 'ABC Auctions: Bidding has ended on {{lot}} and your bid did not win. See other lots: {{link}}',
    subject: 'Bidding has ended on {{lot}}',
    email: 'Bidding has ended on {{lot}} and your bid did not win. Any deposit for this auction is released when the auction is settled.\n\nSee other lots: {{link}}',
    example: { lot: LOT, link: `${WEB}/auctions` },
  },
  {
    key: 'invoice_issued', version: 1, category: 'transactional', preference: 'payments', policy: 'invoice', channels: ALL,
    text: 'ABC Auctions: Invoice {{invoice}} for {{total}} is ready. Please pay by {{due}}: {{link}}',
    subject: 'Invoice {{invoice}}: please pay by {{due}}',
    email: 'Your invoice {{invoice}} for {{total}} is ready. It shows every fee and tax.\n\nPlease pay by {{due}}. You can pay from your wallet or by mobile money in the app: {{link}}',
    example: { invoice: 'HRE-V-2611-0004', total: 'US$28,175.00', due: 'Thu 8 Oct, 14:30', link: INVOICE_LINK },
  },
  {
    key: 'payment_reminder', version: 1, category: 'transactional', preference: 'payments', policy: 'payment_reminder', channels: ALL,
    text: 'ABC Auctions reminder: Invoice {{invoice}} for {{total}} is due by {{due}}. Pay here: {{link}}',
    subject: 'Reminder: invoice {{invoice}} is due by {{due}}',
    email: 'This is a reminder that invoice {{invoice}} for {{total}} is due by {{due}}.\n\nPay in the app: {{link}}',
    example: { invoice: 'HRE-V-2611-0004', total: 'US$28,175.00', due: 'Thu 8 Oct, 14:30', link: INVOICE_LINK },
  },
  {
    key: 'payment_reminder_final', version: 1, category: 'transactional', preference: 'payments', policy: 'payment_reminder', channels: ALL,
    text: 'ABC Auctions final reminder: pay {{invoice}} ({{total}}) by {{due}} to keep your deposit. {{link}}',
    subject: 'Final reminder: invoice {{invoice}} is due by {{due}}',
    email: 'Invoice {{invoice}} for {{total}} is due by {{due}}.\n\nIf it is not paid by then, your deposit for this auction may be forfeited and a relisting fee charged, as set out in the rules. Pay in the app: {{link}}',
    example: { invoice: 'HRE-V-2611-0004', total: 'US$28,175.00', due: 'Thu 8 Oct, 14:30', link: INVOICE_LINK },
  },
  {
    key: 'payment_received', version: 1, category: 'transactional', preference: 'payments', policy: 'invoice', channels: ALL,
    text: 'ABC Auctions: We have received {{amount}} for invoice {{invoice}}. Thank you.',
    subject: 'Payment received for invoice {{invoice}}',
    email: 'We have received your payment of {{amount}} for invoice {{invoice}}. Thank you.\n\nWe will tell you when your goods are ready to collect.',
    example: { amount: 'US$28,175.00', invoice: 'HRE-V-2611-0004' },
  },
  {
    key: 'gate_pass_ready', version: 1, category: 'transactional', preference: 'collection', policy: 'collection_ready', channels: ALL,
    text: 'ABC Auctions: Gate pass for {{invoice}} is in the app. Collect in {{branch}} by {{collectBy}}. {{link}}',
    subject: 'Ready to collect: invoice {{invoice}}',
    email: 'Your goods for invoice {{invoice}} are ready. Show the gate pass in the app at our {{branch}} branch and collect by {{collectBy}}.\n\nOpen the gate pass: {{link}}',
    example: { invoice: 'HRE-V-2611-0004', branch: 'Harare', collectBy: 'Sat 10 Oct, 14:30', link: INVOICE_LINK },
  },
  {
    key: 'default_warning', version: 1, category: 'transactional', preference: 'payments', policy: 'default', channels: ALL,
    text: 'ABC Auctions: Invoice {{invoice}} for {{total}} is overdue. Pay now to keep your deposit: {{link}}',
    subject: 'Invoice {{invoice}} is overdue',
    email: 'Invoice {{invoice}} for {{total}} was not paid in time.\n\nPlease pay now. If it stays unpaid, your deposit for this auction is forfeited and the lots are offered again, as set out in the rules. Pay in the app: {{link}}',
    example: { invoice: 'HRE-V-2611-0004', total: 'US$28,175.00', link: INVOICE_LINK },
  },
  {
    key: 'deposit_forfeited', version: 1, category: 'transactional', preference: 'payments', policy: 'default', channels: ALL,
    text: 'ABC Auctions: Invoice {{invoice}} was not paid in time. It is cancelled and your deposit of {{deposit}} is forfeited.',
    subject: 'Invoice {{invoice}} cancelled; deposit forfeited',
    email: 'Invoice {{invoice}} was not paid in time, so it is cancelled and the lots will be offered again.\n\nYour deposit of {{deposit}} for this auction is forfeited, as set out in the rules.',
    example: { invoice: 'HRE-V-2611-0004', deposit: 'US$3,000.00' },
  },
  {
    key: 'invoice_cancelled', version: 1, category: 'transactional', preference: 'payments', policy: 'default', channels: ALL,
    text: 'ABC Auctions: Invoice {{invoice}} was not paid in time and is cancelled. The lots will be offered again.',
    subject: 'Invoice {{invoice}} cancelled',
    email: 'Invoice {{invoice}} was not paid in time, so it is cancelled and the lots will be offered again.',
    example: { invoice: 'HRE-V-2611-0004' },
  },
  {
    key: 'title_step_overdue', version: 1, category: 'transactional', preference: 'staff_tasks', policy: 'staff_task', channels: ALL,
    text: 'ABC staff: {{step}} for {{lot}} was due {{due}} and is not done. Please update the title tracker.',
    subject: 'Overdue: {{step}} for {{lot}}',
    email: '{{step}} for {{lot}} was due {{due}} and is not marked done.\n\nPlease complete it or record why it is delayed in the title tracker. The buyer cannot collect until every step is done.',
    example: { step: 'ZIMRA clearance', lot: LOT, due: 'Thu 22 Oct, 14:30' },
  },
  {
    key: 'title_complete', version: 1, category: 'transactional', preference: 'collection', policy: 'collection_ready', channels: ALL,
    text: 'ABC Auctions: Papers for {{lot}} are done. Collect it in {{branch}} with your gate pass. {{link}}',
    subject: 'Papers complete: {{lot}} is ready to collect',
    email: 'Police clearance, ZIMRA clearance and the change of ownership for {{lot}} are complete.\n\nShow your gate pass in the app at our {{branch}} branch to collect it: {{link}}',
    example: { lot: LOT, branch: 'Harare', link: INVOICE_LINK },
  },
  {
    key: 'payout_scheduled', version: 1, category: 'transactional', preference: 'selling', policy: 'payout', channels: ALL,
    text: 'ABC Auctions: A payout of {{amount}} is scheduled for {{due}}. See your statement in the app.',
    subject: 'Payout of {{amount}} scheduled',
    email: 'A payout of {{amount}} is scheduled for {{due}}, after the claim window.\n\nYour statement in the app shows each lot, the commission and any deductions.',
    example: { amount: 'US$22,050.00', due: 'Tue 13 Oct' },
  },
  {
    key: 'payout_paid', version: 1, category: 'transactional', preference: 'selling', policy: 'payout', channels: ALL,
    text: 'ABC Auctions: We have sent your payout of {{amount}}. Reference {{reference}}.',
    subject: 'Payout of {{amount}} sent',
    email: 'We have sent your payout of {{amount}}. The payment reference is {{reference}}.\n\nIt may take a working day to reach your account.',
    example: { amount: 'US$22,050.00', reference: 'CBZ-20261013-0042' },
  },
  {
    key: 'payout_blocked', version: 1, category: 'transactional', preference: 'selling', policy: 'payout', channels: ALL,
    text: 'ABC Auctions: Your payout for invoice {{invoice}} is on hold: {{reason}}. We will tell you when it is released.',
    subject: 'Payout on hold for invoice {{invoice}}',
    email: 'Your payout for the lots on invoice {{invoice}} is on hold: {{reason}}.\n\nNothing is lost. We will tell you as soon as it is released.',
    example: { invoice: 'HRE-V-2611-0004', reason: 'commission rates are still being confirmed' },
  },
  {
    key: 'registration_approved', version: 1, category: 'transactional', preference: 'account', policy: 'registration', channels: ALL,
    text: 'ABC Auctions: You are registered for {{auction}}. You can bid now.',
    subject: 'You are registered for {{auction}}',
    email: 'You are registered for {{auction}} and can bid now. Your limit is shown on every lot before you confirm a bid.',
    example: { auction: 'Vehicles: Harare, October' },
  },
  {
    key: 'registration_review', version: 1, category: 'transactional', preference: 'account', policy: 'registration', channels: ALL,
    text: 'ABC Auctions: Your registration for {{auction}} needs a quick check by our team. We will tell you when it is done.',
    subject: 'Your registration for {{auction}} is being checked',
    email: 'Your registration for {{auction}} needs a quick check by our team before you can bid. We will tell you when it is done.',
    example: { auction: 'Vehicles: Harare, October' },
  },
  {
    key: 'otp_code', version: 1, category: 'transactional', preference: null, policy: 'otp', channels: ['whatsapp', 'sms', 'email'],
    text: 'ABC Auctions: Your sign-in code is {{code}}. It expires in {{minutes}} minutes. Do not share it with anyone.',
    subject: 'Your ABC Auctions sign-in code',
    email: 'Your sign-in code is {{code}}. It expires in {{minutes}} minutes.\n\nDo not share it with anyone. ABC staff will never ask for it. If you did not ask for this code, you can ignore this email.',
    example: { code: '482913', minutes: '10' },
  },
  {
    key: 'consignment_received', version: 1, category: 'transactional', preference: 'selling', policy: 'consignment', channels: ALL,
    text: 'ABC Auctions: We have received the details of {{title}} (ref {{ref}}). Our intake team will send your valuation and consignment note.',
    subject: 'We have received {{title}}',
    email: 'We have received the details of {{title}} (reference {{ref}}).\n\nOur intake team will check them and send you a valuation range and your consignment note to sign in the app.',
    example: { title: 'Samsung 55-inch TV', ref: 'HRE-26-9C1D0B7E' },
  },
  {
    key: 'chat_reply', version: 1, category: 'transactional', preference: null, policy: null, channels: ['whatsapp'],
    text: '{{text}}',
    subject: '',
    email: '',
    example: { text: 'Welcome to ABC Auctions selling. What are you selling?' },
  },
];

const BY_KEY = new Map(TEMPLATE_LIBRARY.map((t) => [t.key, t]));

export function templateDefinition(key: string): TemplateDefinition {
  const t = BY_KEY.get(key);
  if (!t) throw new Error(`Unknown template ${key}`);
  return t;
}

/** WhatsApp template name as submitted to Meta. Chat replies are session messages, not templates. */
export function providerTemplateName(t: TemplateDefinition): string | null {
  return t.policy === null && t.preference === null ? null : `abc_${t.key}_v${t.version}`;
}

export interface TemplateRow {
  key: string;
  version: number;
  channel: Channel;
  locale: string;
  category: TemplateCategory;
  subject: string | null;
  body: string;
  providerTemplateName: string | null;
}

/** The comms.template rows for the library, one per template and channel. */
export function templateRows(library: readonly TemplateDefinition[] = TEMPLATE_LIBRARY): TemplateRow[] {
  const rows: TemplateRow[] = [];
  for (const t of library) {
    for (const channel of t.channels) {
      rows.push({
        key: t.key,
        version: t.version,
        channel,
        locale: DEFAULT_LOCALE,
        category: t.category,
        subject: channel === 'email' || channel === 'push' || channel === 'in_app' ? t.subject : null,
        body: channel === 'email' ? `${t.email}${EMAIL_FOOTER}` : t.text,
        providerTemplateName: channel === 'whatsapp' ? providerTemplateName(t) : null,
      });
    }
  }
  return rows;
}

function sqlString(s: string | null): string {
  if (s === null) return 'NULL';
  return s.includes('\n') ? `E'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'` : `'${s.replace(/'/g, "''")}'`;
}

export const TEMPLATE_SQL_BEGIN = '-- BEGIN comms template library (generated: pnpm --filter @abc/comms templates:sql)';
export const TEMPLATE_SQL_END = '-- END comms template library';

/** INSERT statements for the library, as pasted into db/seed.sql and migration 0002. */
export function templatesSql(rows: readonly TemplateRow[] = templateRows()): string {
  const values = rows.map(
    (r) =>
      `  (${sqlString(r.key)}, ${r.version}, ${sqlString(r.channel)}, ${sqlString(r.locale)}, ${sqlString(r.category)}, ${sqlString(r.subject)}, ${sqlString(r.body)}, ${sqlString(r.providerTemplateName)}, 'approved')`,
  );
  return [
    TEMPLATE_SQL_BEGIN,
    'INSERT INTO comms.template (key, version, channel, locale, category, subject, body, provider_template_name, status) VALUES',
    values.join(',\n'),
    'ON CONFLICT (key, version, channel, locale) DO NOTHING;',
    TEMPLATE_SQL_END,
  ].join('\n');
}

/** Parameters a template needs, across all its channels. */
export function templateParams(t: TemplateDefinition): string[] {
  return [...new Set([...placeholders(t.text), ...placeholders(t.subject), ...placeholders(t.email)])];
}
